name: Zizmor

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["**"]

permissions: {}

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
jobs:
    zizmor:
        runs-on: ubuntu-latest
        name: zizmor
        permissions:
            security-events: write # required to upload results to Github Advanced Security
        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
            - name: Run zizmor 🌈
              uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
